export const HS2_CHAPTER_NAMES: Record<string, string> = {
    '01': 'Live Animals',
    '02': 'Meat & Edible Offal',
    '03': 'Fish & Crustaceans',
    '04': 'Dairy & Eggs',
    '05': 'Animal Products n.e.s.',
    '06': 'Live Trees & Plants',
    '07': 'Edible Vegetables',
    '08': 'Edible Fruit & Nuts',
    '09': 'Coffee, Tea & Spices',
    '10': 'Cereals',
    '11': 'Milling Industry Products',
    '12': 'Oil Seeds & Fruit',
    '13': 'Lac, Gums & Resins',
    '14': 'Vegetable Plaiting Materials',
    '15': 'Animal/Veg Fats & Oils',
    '16': 'Meat/Fish Preparations',
    '17': 'Sugars & Confectionery',
    '18': 'Cocoa & Preparations',
    '19': 'Cereal/Flour Preparations',
    '20': 'Veg/Fruit Preparations',
    '21': 'Miscellaneous Edibles',
    '22': 'Beverages, Spirits & Vinegar',
    '23': 'Food Industry Residues',
    '24': 'Tobacco & Substitutes',
    '25': 'Salt, Sulphur & Earths',
    '26': 'Ores, Slag & Ash',
    '27': 'Mineral Fuels & Oils',
    '28': 'Inorganic Chemicals',
    '29': 'Organic Chemicals',
    '30': 'Pharmaceutical Products',
    '31': 'Fertilizers',
    '32': 'Tanning/Dyeing Extracts',
    '33': 'Essential Oils & Cosmetics',
    '34': 'Soap & Lubes',
    '35': 'Albuminoids & Glues',
    '36': 'Explosives & Pyrotechnics',
    '37': 'Photographic Goods',
    '38': 'Miscellaneous Chemicals',
    '39': 'Plastics & Articles',
    '40': 'Rubber & Articles',
    '41': 'Raw Hides & Skins',
    '42': 'Leather Articles',
    '43': 'Furskins & Articles',
    '44': 'Wood & Articles',
    '45': 'Cork & Articles',
    '46': 'Straw/Plaiting Articles',
    '47': 'Pulp of Wood',
    '48': 'Paper & Paperboard',
    '49': 'Printed Books & Newspapers',
    '50': 'Silk',
    '51': 'Wool & Animal Hair',
    '52': 'Cotton',
    '53': 'Other Vegetable Fibers',
    '54': 'Man-made Filaments',
    '55': 'Man-made Staple Fibers',
    '56': 'Wadding, Felt & Nonwovens',
    '57': 'Carpets & Floor Coverings',
    '58': 'Special Woven Fabrics',
    '59': 'Impregnated Fabrics',
    '60': 'Knitted/Crocheted Fabrics',
    '61': 'Knitted Apparel',
    '62': 'Non-knitted Apparel',
    '63': 'Other Textile Articles',
    '64': 'Footwear & Parts',
    '65': 'Headgear & Parts',
    '66': 'Umbrellas & Walking-sticks',
    '67': 'Prepared Feathers/Down',
    '68': 'Stone/Plaster Articles',
    '69': 'Ceramic Products',
    '70': 'Glass & Glassware',
    '71': 'Pearls, Precious Stones & Metals',
    '72': 'Iron & Steel',
    '73': 'Iron or Steel Articles',
    '74': 'Copper & Articles',
    '75': 'Nickel & Articles',
    '76': 'Aluminum & Articles',
    '77': 'Reserved (Chapter 77)',
    '78': 'Lead & Articles',
    '79': 'Zinc & Articles',
    '80': 'Tin & Articles',
    '81': 'Other Base Metals',
    '82': 'Tools & Cutlery',
    '83': 'Misc Base Metal Articles',
    '84': 'Nuclear Reactors & Machinery',
    '85': 'Electrical Machinery',
    '86': 'Railway/Tramway Locomotives',
    '87': 'Vehicles & Parts (Automotive)',
    '88': 'Aircraft & Spacecraft',
    '89': 'Ships & Boats',
    '90': 'Optical/Medical Instruments',
    '91': 'Clocks & Watches',
    '92': 'Musical Instruments',
    '93': 'Arms & Ammunition',
    '94': 'Furniture & Bedding',
    '95': 'Toys & Sports Equipment',
    '96': 'Miscellaneous Manufactures',
    '97': 'Works of Art & Antiques',
    '98': 'Special Classification Provisions',
    '99': 'Special Classification Provisions'
};
