// src/features/regime-digest/lib/metricCatalog.ts
import type { MetricDef } from './types';

export const DIGEST_METRICS: MetricDef[] = [
  {
    id: 'BIS_GLOBAL_LIQUIDITY_USD_BN',
    name: 'Global Net Liquidity',
    section: 'liquidity',
    unit: 'USD bn',
    sourceFamily: 'BIS/GQ',
    min: 5_000,
    max: 100_000,
    staleDays: 45,
    glossaryPath: '/glossary/net-liquidity-z-score/',
    format: 'number',
    decimals: 0,
  },
  {
    id: 'DXY_INDEX',
    name: 'DXY',
    section: 'rates_usd',
    unit: 'index',
    sourceFamily: 'market',
    min: 70,
    max: 130,
    staleDays: 7,
    format: 'number',
    decimals: 2,
  },
  {
    id: 'VIX_INDEX',
    name: 'VIX',
    section: 'vol',
    unit: 'index',
    sourceFamily: 'market',
    min: 5,
    max: 100,
    staleDays: 7,
    format: 'number',
    decimals: 2,
  },
  {
    id: 'GOLD_PRICE_USD',
    name: 'Gold',
    section: 'metals',
    unit: 'USD/oz',
    sourceFamily: 'market',
    min: 500,
    max: 10_000,
    staleDays: 7,
    format: 'usd',
    decimals: 0,
  },
  {
    id: 'RATIO_DEBT_GOLD',
    name: 'Debt/Gold',
    section: 'metals',
    unit: 'x',
    sourceFamily: 'GQ',
    min: 1,
    max: 200,
    staleDays: 14,
    format: 'ratio',
    decimals: 2,
  },
  {
    id: 'BRENT_CRUDE_PRICE',
    name: 'Brent',
    section: 'energy',
    unit: 'USD/bbl',
    sourceFamily: 'market',
    min: 10,
    max: 300,
    staleDays: 7,
    format: 'usd',
    decimals: 2,
  },
  {
    id: 'US_CPI_YOY',
    name: 'US CPI YoY',
    section: 'us',
    unit: '%',
    sourceFamily: 'FRED',
    min: -5,
    max: 25,
    staleDays: 45,
    format: 'percent',
    decimals: 2,
  },
  {
    id: 'IN_GDP_GROWTH_YOY',
    name: 'India GDP YoY',
    section: 'india',
    unit: '%',
    sourceFamily: 'MOSPI',
    min: -15,
    max: 20,
    staleDays: 120,
    format: 'percent',
    decimals: 2,
  },
  {
    id: 'IN_CPI_YOY',
    name: 'India CPI YoY',
    section: 'india',
    unit: '%',
    sourceFamily: 'MOSPI',
    min: -5,
    max: 25,
    staleDays: 45,
    format: 'percent',
    decimals: 2,
  },
  {
    id: 'CN_GDP_GROWTH_YOY',
    name: 'China GDP YoY',
    section: 'china',
    unit: '%',
    sourceFamily: 'NBS',
    min: -15,
    max: 20,
    staleDays: 120,
    format: 'percent',
    decimals: 2,
  },
];

/** Core set for publish quality gate */
export const CORE_METRIC_IDS = [
  'BIS_GLOBAL_LIQUIDITY_USD_BN',
  'DXY_INDEX',
  'VIX_INDEX',
  'GOLD_PRICE_USD',
  'US_CPI_YOY',
] as const;
