import React, { useEffect, useState } from 'react';
import { useParams, Link } from 'react-router-dom';
import { supabase } from '@/lib/supabase';
import { SEOManager } from '@/components/SEOManager';
import { ArrowLeft, ChevronRight, Home, Newspaper } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Card, CardContent } from '@/components/ui/card';

interface Digest {
    id: string;
    year_month: string;
    html_content: string;
    plain_text: string;
    subject_line: string;
    created_at: string;
}

export const RegimeDigestPage: React.FC = () => {
    const { year, month } = useParams<{ year: string; month: string }>();
    const [digest, setDigest] = useState<Digest | null>(null);
    const [loading, setLoading] = useState(true);
    const [error, setError] = useState<string | null>(null);

    useEffect(() => {
        const fetchDigest = async () => {
            if (!year || !month) return;
            const ym = `${year}-${month}`;

            const { data, error } = await supabase
                .from('monthly_regime_digests')
                .select('*')
                .eq('year_month', ym)
                .single();

            if (error) {
                setError("Digest not found.");
            } else {
                setDigest(data);
            }
            setLoading(false);
        };

        fetchDigest();
    }, [year, month]);

    if (loading) {
        return (
            <div className="min-h-[80vh] flex items-center justify-center">
                <span className="text-sm font-black text-muted-foreground/30 uppercase tracking-uppercase animate-pulse">Loading Digest...</span>
            </div>
        );
    }
    
    if (error || !digest) {
        return (
            <div className="max-w-4xl mx-auto py-12 px-4">
                <div className="p-6 rounded-xl border border-rose-500/30 bg-rose-500/10 text-rose-400 font-bold text-center">
                    {error || "Digest not found"}
                </div>
                <div className="mt-8 text-center">
                    <Button asChild variant="outline">
                        <Link to="/regime-digest">
                            <ArrowLeft className="mr-2 h-4 w-4" /> Back to Archive
                        </Link>
                    </Button>
                </div>
            </div>
        );
    }

    // Sanitize or wrap HTML safely
    // Since the HTML is generated by our own trusted Edge Function, we can render it.
    // However, the email HTML has its own <html> and <body> tags which we should strip or render in an iframe or shadow DOM.
    // For simplicity, we'll strip the outer tags and inject into a div, as the inline styles should work.
    const cleanHtml = digest.html_content
        .replace(/<!DOCTYPE html>/i, '')
        .replace(/<html>/i, '')
        .replace(/<\/html>/i, '')
        .replace(/<body[^>]*>/i, '<div style="background-color:#020617; color:#f8fafc; font-family: ui-sans-serif, system-ui, sans-serif; letter-spacing: 0.025em; padding: 24px; border-radius: 12px;">') // Replace body with div to inherit styles but keep bg
        .replace(/<\/body>/i, '</div>');

    return (
        <div className="w-full max-w-4xl mx-auto py-12 px-4 sm:px-6">
            <SEOManager
                title={digest.subject_line}
                description={digest.plain_text.substring(0, 160)}
                canonicalUrl={`https://graphiquestor.com/regime-digest/${year}/${month}`}
                jsonLd={{
                    "@context": "https://schema.org",
                    "@type": "NewsArticle",
                    "headline": digest.subject_line,
                    "dateline": digest.year_month,
                    "description": digest.plain_text.substring(0, 160) + "...",
                    "datePublished": digest.created_at,
                    "author": {
                        "@type": "Organization",
                        "name": "GraphiQuestor Macro Team"
                    },
                    "publisher": {
                        "@type": "Organization",
                        "name": "GraphiQuestor",
                        "logo": {
                            "@type": "ImageObject",
                            "url": "https://graphiquestor.com/logo.png"
                        }
                    }
                }}
            />
            
            {/* Breadcrumb Schema */}
            <script type="application/ld+json">
                {JSON.stringify({
                    "@context": "https://schema.org",
                    "@type": "BreadcrumbList",
                    "itemListElement": [{
                        "@type": "ListItem",
                        "position": 1,
                        "name": "Home",
                        "item": "https://graphiquestor.com"
                    }, {
                        "@type": "ListItem",
                        "position": 2,
                        "name": "Regime Digest Archive",
                        "item": "https://graphiquestor.com/regime-digest"
                    }, {
                        "@type": "ListItem",
                        "position": 3,
                        "name": digest.year_month,
                        "item": `https://graphiquestor.com/regime-digest/${year}/${month}`
                    }]
                })}
            </script>

            <div className="mb-8">
                {/* Breadcrumbs */}
                <nav className="flex items-center space-x-2 text-xs font-bold uppercase tracking-uppercase text-muted-foreground/60 mb-6">
                    <Link to="/" className="hover:text-white transition-colors flex items-center gap-1">
                        <Home size={14} />
                        Home
                    </Link>
                    <ChevronRight size={14} className="text-muted-foreground/30" />
                    <Link to="/regime-digest" className="hover:text-white transition-colors flex items-center gap-1">
                        <Newspaper size={14} />
                        Regime Digest
                    </Link>
                    <ChevronRight size={14} className="text-muted-foreground/30" />
                    <span className="text-blue-400">{digest.year_month}</span>
                </nav>

                <Button asChild variant="ghost" className="text-muted-foreground hover:text-white -ml-4">
                    <Link to="/regime-digest">
                        <ArrowLeft className="mr-2 h-4 w-4" /> Back to Archive
                    </Link>
                </Button>
            </div>
            
            <h1 className="text-2xl sm:text-4xl font-black text-white mb-8 tracking-heading leading-tight uppercase">
                {digest.subject_line}
            </h1>
            
            {/* Render the Email Content */}
            <Card variant="elevated" className="overflow-hidden border-white/10 bg-slate-950 shadow-2xl">
                <CardContent className="p-0 sm:p-2">
                    <div 
                        dangerouslySetInnerHTML={{ __html: cleanHtml }} 
                        className="prose prose-invert prose-slate max-w-none prose-headings:font-black prose-headings:tracking-heading prose-a:text-blue-400 hover:prose-a:text-blue-300"
                    />
                </CardContent>
            </Card>

            <div className="mt-12 text-center p-10 bg-slate-900/50 border border-white/5 rounded-2xl backdrop-blur-md">
                <h3 className="text-xl font-black text-white uppercase tracking-heading mb-3">
                    Want this delivered to your inbox?
                </h3>
                <p className="text-sm font-bold text-muted-foreground/60 mb-8 max-w-md mx-auto">
                    Get institutional-grade macro intelligence, liquidity monitoring, and sovereign stress telemetry direct to your inbox monthly.
                </p>
                <div className="flex justify-center flex-wrap gap-4">
                    <Button asChild variant="contained" size="lg" className="bg-blue-600 hover:bg-blue-700 text-white font-black px-8">
                        <a href="https://graphiquestor.com/#newsletter">
                            Subscribe for Free
                        </a>
                    </Button>
                    <Button asChild variant="outline" size="lg" className="border-white/10">
                        <Link to="/">
                            Launch Terminal
                        </Link>
                    </Button>
                </div>
            </div>
        </div>
    );
};
