import React, { useEffect, useState } from 'react';
import { useParams, Link } from 'react-router-dom';
import { supabase } from '@/lib/supabase';
import { Container, Typography, Box, Button, Breadcrumbs, CircularProgress, Alert } from '@mui/material';
import { SEOManager } from '@/components/SEOManager';
import ArrowBackIcon from '@mui/icons-material/ArrowBack';

interface Digest {
    id: string;
    year_month: string;
    html_content: string;
    plain_text: string;
    subject_line: string;
    generated_at: string;
}

export const RegimeDigestPage: React.FC = () => {
    const { year, month } = useParams();
    const [digest, setDigest] = useState<Digest | null>(null);
    const [loading, setLoading] = useState(true);
    const [error, setError] = useState<string | null>(null);

    useEffect(() => {
        const fetchDigest = async () => {
            if (!year || !month) return;
            const ym = `${year}-${month}`;

            const { data, error } = await supabase
                .from('monthly_regime_digests')
                .select('*')
                .eq('year_month', ym)
                .single();

            if (error) {
                setError("Digest not found.");
            } else {
                setDigest(data);
            }
            setLoading(false);
        };

        fetchDigest();
    }, [year, month]);

    if (loading) return <Box sx={{ height: '80vh', display: 'flex', alignItems: 'center', justifyContent: 'center' }}><CircularProgress /></Box>;
    if (error || !digest) return <Container sx={{ py: 8 }}><Alert severity="error">{error || "Digest not found"}</Alert></Container>;

    // Sanitize or wrap HTML safely
    // Since the HTML is generated by our own trusted Edge Function, we can render it.
    // However, the email HTML has its own <html> and <body> tags which we should strip or render in an iframe or shadow DOM.
    // For simplicity, we'll strip the outer tags and inject into a div, as the inline styles should work.
    const cleanHtml = digest.html_content
        .replace(/<!DOCTYPE html>/i, '')
        .replace(/<html>/i, '')
        .replace(/<\/html>/i, '')
        .replace(/<body[^>]*>/i, '<div style="background-color:#111; color:#ddd;">') // Replace body with div to inherit styles but keep bg
        .replace(/<\/body>/i, '</div>');

    return (
        <>
            <SEOManager
                title={digest.subject_line}
                description={digest.plain_text.substring(0, 160)}
                canonicalUrl={`https://graphiquestor.com/regime-digest/${year}/${month}`}
                jsonLd={{
                    "@context": "https://schema.org",
                    "@type": "NewsArticle",
                    "headline": digest.subject_line,
                    "dateline": digest.year_month,
                    "description": digest.plain_text.substring(0, 160) + "...",
                    "datePublished": digest.generated_at,
                    "author": {
                        "@type": "Organization",
                        "name": "GraphiQuestor Macro Team"
                    },
                    "publisher": {
                        "@type": "Organization",
                        "name": "GraphiQuestor",
                        "logo": {
                            "@type": "ImageObject",
                            "url": "https://graphiquestor.com/logo.png"
                        }
                    }
                }}
            />
            {/* Breadcrumb Schema */}
            <script type="application/ld+json">
                {JSON.stringify({
                    "@context": "https://schema.org",
                    "@type": "BreadcrumbList",
                    "itemListElement": [{
                        "@type": "ListItem",
                        "position": 1,
                        "name": "Home",
                        "item": "https://graphiquestor.com"
                    }, {
                        "@type": "ListItem",
                        "position": 2,
                        "name": "Regime Digest Archive",
                        "item": "https://graphiquestor.com/regime-digest"
                    }, {
                        "@type": "ListItem",
                        "position": 3,
                        "name": digest.year_month,
                        "item": `https://graphiquestor.com/regime-digest/${year}/${month}`
                    }]
                })}
            </script>
            <Container maxWidth="md" sx={{ py: 4 }}>
                <Box mb={4}>
                    <Breadcrumbs aria-label="breadcrumb" sx={{ mb: 2 }}>
                        <Link to="/" style={{ color: '#888', textDecoration: 'none' }}>Home</Link>
                        <Link to="/regime-digest" style={{ color: '#888', textDecoration: 'none' }}>Regime Digest</Link>
                        <Typography color="text.primary">{digest.year_month}</Typography>
                    </Breadcrumbs>

                    <Button component={Link} to="/regime-digest" startIcon={<ArrowBackIcon />} sx={{ mb: 2 }}>
                        Back to Archive
                    </Button>
                </Box>

                {/* Render the Email Content */}
                <Box
                    sx={{
                        border: '1px solid',
                        borderColor: 'divider',
                        borderRadius: 2,
                        overflow: 'hidden',
                        bgcolor: '#111'
                    }}
                >
                    <div dangerouslySetInnerHTML={{ __html: cleanHtml }} />
                </Box>

                <Box mt={6} textAlign="center" p={4} bgcolor="background.paper" borderRadius={2}>
                    <Typography variant="h6" gutterBottom>
                        Want this delivered to your inbox?
                    </Typography>
                    <Button variant="contained" color="primary" size="large" href="https://graphiquestor.com/#newsletter">
                        Subscribe for Free
                    </Button>
                </Box>
            </Container>
        </>
    );
};
