export type RelatedKind = 'data' | 'glossary' | 'brief' | 'lab';

export interface RelatedLink {
  to: string;
  label: string;
  kind: RelatedKind;
}

export const contentRelations: Record<string, RelatedLink[]> = {
  '/': [
    { to: '/labs/shadow-system', label: 'Shadow System Lab', kind: 'lab' },
    { to: '/labs/us-macro-fiscal', label: 'US Fiscal Lab', kind: 'lab' },
    { to: '/methods/net-liquidity-z-score', label: 'Net Liquidity Methodology', kind: 'brief' },
    { to: '/glossary/net-liquidity-z-score', label: 'Net Liquidity Z-Score', kind: 'glossary' },
    { to: '/glossary/tga', label: 'Treasury General Account', kind: 'glossary' },
    { to: '/glossary/macro-regime-classification', label: 'Regime Classification', kind: 'glossary' },
  ],
  '/intel/india': [
    { to: '/trade', label: 'India Trade Pulse', kind: 'data' },
    { to: '/labs/de-dollarization-gold', label: 'RBI Gold Accumulation', kind: 'lab' },
    { to: '/methods/india-credit-cycle-clock', label: 'Credit Cycle Methodology', kind: 'brief' },
    { to: '/glossary/loan-to-job-efficiency', label: 'Loan-to-Job Efficiency', kind: 'glossary' },
    { to: '/glossary/energy-dependency-ratio', label: 'Energy Dependency Ratio', kind: 'glossary' },
    { to: '/glossary/foreign-exchange-reserves', label: 'FX Reserve Framework', kind: 'glossary' },
  ],
  '/intel/china': [
    { to: '/labs/china-15th-fyp', label: 'China 15th FYP', kind: 'lab' },
    { to: '/labs/de-dollarization-gold', label: 'PBOC Gold Accumulation', kind: 'lab' },
    { to: '/labs/brics-trade-settlement', label: 'BRICS Settlement', kind: 'lab' },
    { to: '/trade', label: 'China Trade Flows', kind: 'data' },
    { to: '/glossary/petrodollar-system', label: 'Petroyuan vs Petrodollar', kind: 'glossary' },
  ],
  '/trade': [
    { to: '/intel/india', label: 'India Macro Intel', kind: 'data' },
    { to: '/intel/china', label: 'China Macro Intel', kind: 'data' },
    { to: '/labs/brics-trade-settlement', label: 'BRICS Trade Settlement', kind: 'lab' },
    { to: '/glossary/current-account-balance', label: 'Current Account', kind: 'glossary' },
    { to: '/glossary/energy-dependency-ratio', label: 'Energy Dependency', kind: 'glossary' },
  ],
  '/macro-observatory': [
    { to: '/', label: 'Main Terminal', kind: 'data' },
    { to: '/labs/us-macro-fiscal', label: 'US Fiscal Lab', kind: 'lab' },
    { to: '/labs/de-dollarization-gold', label: 'Gold & De-Dollarization', kind: 'lab' },
    { to: '/labs/energy-commodities', label: 'Energy Commodities Lab', kind: 'lab' },
    { to: '/regime-digest', label: 'Regime Digest Archive', kind: 'brief' },
  ],
  '/labs/us-macro-fiscal': [
    { to: '/methods/fiscal-dominance-meter', label: 'Fiscal Dominance Meter', kind: 'brief' },
    { to: '/methods/net-liquidity-z-score', label: 'Net Liquidity Methodology', kind: 'brief' },
    { to: '/labs/shadow-system', label: 'Funding Plumbing Lab', kind: 'lab' },
    { to: '/glossary/fiscal-dominance', label: 'Fiscal Dominance', kind: 'glossary' },
    { to: '/glossary/public-debt-to-gdp', label: 'Public Debt to GDP', kind: 'glossary' },
    { to: '/glossary/interest-expense-to-tax-revenue', label: 'Interest / Tax Revenue', kind: 'glossary' },
  ],
  '/labs/de-dollarization-gold': [
    { to: '/labs/central-bank-gold-purchases', label: 'Central Bank Gold', kind: 'lab' },
    { to: '/labs/petrodollar-decay-indicators', label: 'Petrodollar Decay', kind: 'lab' },
    { to: '/methods/m2-gold-ratio', label: 'M2/Gold Ratio Methodology', kind: 'brief' },
    { to: '/methods/de-dollarization-guide', label: 'De-Dollarization Guide', kind: 'brief' },
    { to: '/glossary/de-dollarization', label: 'De-Dollarization', kind: 'glossary' },
    { to: '/glossary/gold-silver-ratio', label: 'Gold/Silver Ratio', kind: 'glossary' },
  ],
  '/labs/central-bank-gold-purchases': [
    { to: '/labs/de-dollarization-gold', label: 'Gold Reserve Shifts', kind: 'lab' },
    { to: '/intel/india', label: 'RBI Gold Strategy', kind: 'data' },
    { to: '/intel/china', label: 'PBOC Gold Strategy', kind: 'data' },
    { to: '/methods/debt-gold-z-score', label: 'Debt/Gold Z-Score', kind: 'brief' },
    { to: '/glossary/central-bank-gold-purchases', label: 'CB Gold Purchases', kind: 'glossary' },
  ],
  '/labs/brics-trade-settlement': [
    { to: '/trade', label: 'Global Trade Flows', kind: 'data' },
    { to: '/intel/china', label: 'China in BRICS', kind: 'data' },
    { to: '/intel/india', label: 'India in BRICS', kind: 'data' },
    { to: '/labs/de-dollarization-gold', label: 'BRICS Gold Reserves', kind: 'lab' },
    { to: '/glossary/petrodollar-system', label: 'Petrodollar vs Petroyuan', kind: 'glossary' },
    { to: '/glossary/mbridge', label: 'mBridge CBDC', kind: 'glossary' },
  ],
  '/labs/us-treasury-foreign-holdings': [
    { to: '/labs/de-dollarization-gold', label: 'Reserve Diversification', kind: 'lab' },
    { to: '/labs/us-macro-fiscal', label: 'US Fiscal Stress', kind: 'lab' },
    { to: '/labs/shadow-system', label: 'Treasury Market Plumbing', kind: 'lab' },
    { to: '/glossary/tga', label: 'Treasury General Account', kind: 'glossary' },
    { to: '/glossary/sovereign-rollover-risk', label: 'Sovereign Rollover Risk', kind: 'glossary' },
  ],
  '/labs/petrodollar-decay-indicators': [
    { to: '/labs/de-dollarization-gold', label: 'Gold Reserve Shift', kind: 'lab' },
    { to: '/labs/energy-commodities', label: 'Energy Commodities Lab', kind: 'lab' },
    { to: '/intel/china', label: 'Petroyuan Dynamics', kind: 'data' },
    { to: '/methods/energy-dependency-ratio', label: 'Energy Dependency Ratio', kind: 'brief' },
    { to: '/glossary/petrodollar-system', label: 'Petrodollar System', kind: 'glossary' },
    { to: '/glossary/gold-oil-ratio', label: 'Gold/Oil Ratio', kind: 'glossary' },
  ],
  '/labs/energy-commodities': [
    { to: '/labs/petrodollar-decay-indicators', label: 'Petrodollar Decay', kind: 'lab' },
    { to: '/intel/china', label: 'China Energy Demand', kind: 'data' },
    { to: '/intel/india', label: 'India Energy Imports', kind: 'data' },
    { to: '/methods/energy-dependency-ratio', label: 'Energy Dependency Ratio', kind: 'brief' },
    { to: '/glossary/gold-oil-ratio', label: 'Gold/Oil Ratio Signal', kind: 'glossary' },
  ],
  '/labs/sovereign-stress': [
    { to: '/labs/us-macro-fiscal', label: 'US Fiscal Lab', kind: 'lab' },
    { to: '/labs/shadow-system', label: 'Shadow Banking Stress', kind: 'lab' },
    { to: '/methods/fiscal-dominance-meter', label: 'Fiscal Dominance Meter', kind: 'brief' },
    { to: '/glossary/fiscal-dominance', label: 'Fiscal Dominance', kind: 'glossary' },
    { to: '/glossary/public-debt-to-gdp', label: 'Public Debt/GDP', kind: 'glossary' },
    { to: '/glossary/sovereign-rollover-risk', label: 'Sovereign Rollover Risk', kind: 'glossary' },
  ],
  '/labs/shadow-system': [
    { to: '/labs/us-macro-fiscal', label: 'US Fiscal Lab', kind: 'lab' },
    { to: '/labs/us-treasury-foreign-holdings', label: 'Treasury Demand Lab', kind: 'lab' },
    { to: '/methods/net-liquidity-z-score', label: 'Net Liquidity Methodology', kind: 'brief' },
    { to: '/glossary/net-liquidity-z-score', label: 'Net Liquidity Z-Score', kind: 'glossary' },
    { to: '/glossary/reverse-repo-facility-rrp', label: 'Reverse Repo Facility', kind: 'glossary' },
    { to: '/glossary/sofr', label: 'SOFR Funding Stress', kind: 'glossary' },
  ],
  '/labs/china-15th-fyp': [
    { to: '/intel/china', label: 'China Macro Intel', kind: 'data' },
    { to: '/labs/energy-commodities', label: 'China Energy Transition', kind: 'lab' },
    { to: '/labs/brics-trade-settlement', label: 'BRICS Trade Settlement', kind: 'lab' },
    { to: '/trade', label: 'China Trade Flows', kind: 'data' },
  ],
  '/labs/africa-macro': [
    { to: '/labs/de-dollarization-gold', label: 'Gold Reserves Shift', kind: 'lab' },
    { to: '/trade', label: 'Africa Trade Flows', kind: 'data' },
    { to: '/labs/brics-trade-settlement', label: 'BRICS Expansion', kind: 'lab' },
    { to: '/glossary/foreign-exchange-reserves', label: 'FX Reserve Framework', kind: 'glossary' },
  ],
  '/methods/net-liquidity-z-score': [
    { to: '/labs/shadow-system', label: 'Shadow System Lab', kind: 'lab' },
    { to: '/labs/us-macro-fiscal', label: 'US Fiscal Lab', kind: 'lab' },
    { to: '/glossary/net-liquidity-z-score', label: 'Net Liquidity Z-Score', kind: 'glossary' },
    { to: '/glossary/tga', label: 'Treasury General Account', kind: 'glossary' },
    { to: '/glossary/reverse-repo-facility-rrp', label: 'Reverse Repo Facility', kind: 'glossary' },
  ],
  '/methods/fiscal-dominance-meter': [
    { to: '/labs/us-macro-fiscal', label: 'US Fiscal Lab', kind: 'lab' },
    { to: '/labs/sovereign-stress', label: 'Sovereign Stress Lab', kind: 'lab' },
    { to: '/methods/net-liquidity-z-score', label: 'Net Liquidity Methodology', kind: 'brief' },
    { to: '/glossary/fiscal-dominance', label: 'Fiscal Dominance', kind: 'glossary' },
    { to: '/glossary/interest-expense-to-tax-revenue', label: 'Interest/Tax Revenue', kind: 'glossary' },
  ],
  '/methods/m2-gold-ratio': [
    { to: '/labs/de-dollarization-gold', label: 'Gold & Reserve Lab', kind: 'lab' },
    { to: '/labs/central-bank-gold-purchases', label: 'Central Bank Gold', kind: 'lab' },
    { to: '/methods/debt-gold-z-score', label: 'Debt/Gold Z-Score', kind: 'brief' },
    { to: '/glossary/m2-gold-ratio', label: 'M2/Gold Ratio', kind: 'glossary' },
    { to: '/glossary/de-dollarization', label: 'Fiat Debasement', kind: 'glossary' },
  ],
  '/methods/debt-gold-z-score': [
    { to: '/labs/de-dollarization-gold', label: 'Gold & Reserve Lab', kind: 'lab' },
    { to: '/labs/us-macro-fiscal', label: 'US Debt Lab', kind: 'lab' },
    { to: '/methods/m2-gold-ratio', label: 'M2/Gold Ratio', kind: 'brief' },
    { to: '/glossary/debt-gold-z-score', label: 'Debt/Gold Z-Score', kind: 'glossary' },
    { to: '/glossary/real-interest-rates', label: 'Real Interest Rates', kind: 'glossary' },
  ],
  '/methods/de-dollarization-guide': [
    { to: '/labs/de-dollarization-gold', label: 'Gold Reserve Lab', kind: 'lab' },
    { to: '/labs/central-bank-gold-purchases', label: 'Central Bank Gold', kind: 'lab' },
    { to: '/labs/petrodollar-decay-indicators', label: 'Petrodollar Decay', kind: 'lab' },
    { to: '/glossary/de-dollarization', label: 'De-Dollarization', kind: 'glossary' },
    { to: '/glossary/petrodollar-system', label: 'Petrodollar System', kind: 'glossary' },
    { to: '/glossary/reserve-currency-composition', label: 'Reserve Composition', kind: 'glossary' },
  ],
  '/methods/fed-monetization-monitor': [
    { to: '/labs/us-macro-fiscal', label: 'US Fiscal Lab', kind: 'lab' },
    { to: '/labs/shadow-system', label: 'Fed Balance Sheet Lab', kind: 'lab' },
    { to: '/methods/net-liquidity-z-score', label: 'Net Liquidity Methodology', kind: 'brief' },
    { to: '/glossary/fiscal-dominance', label: 'Fiscal Dominance', kind: 'glossary' },
    { to: '/glossary/federal-debt-monetisation', label: 'Debt Monetisation', kind: 'glossary' },
  ],
  '/methods/india-credit-cycle-clock': [
    { to: '/intel/india', label: 'India Macro Intel', kind: 'data' },
    { to: '/methods/loan-to-job-efficiency', label: 'Loan-to-Job Efficiency', kind: 'brief' },
    { to: '/trade', label: 'India Trade Flows', kind: 'data' },
    { to: '/glossary/loan-to-job-efficiency', label: 'Loan-to-Job Ratio', kind: 'glossary' },
    { to: '/glossary/current-account-balance', label: 'Current Account', kind: 'glossary' },
  ],
  '/methods/energy-dependency-ratio': [
    { to: '/labs/energy-commodities', label: 'Energy Commodities Lab', kind: 'lab' },
    { to: '/labs/petrodollar-decay-indicators', label: 'Petrodollar Decay Lab', kind: 'lab' },
    { to: '/intel/india', label: 'India Energy Exposure', kind: 'data' },
    { to: '/glossary/energy-dependency-ratio', label: 'Energy Dependency Ratio', kind: 'glossary' },
    { to: '/glossary/gold-oil-ratio', label: 'Gold/Oil Ratio', kind: 'glossary' },
  ],
  '/methods/loan-to-job-efficiency': [
    { to: '/intel/india', label: 'India Employment Data', kind: 'data' },
    { to: '/methods/india-credit-cycle-clock', label: 'India Credit Cycle', kind: 'brief' },
    { to: '/glossary/loan-to-job-efficiency', label: 'Loan-to-Job Efficiency', kind: 'glossary' },
    { to: '/glossary/mospi', label: 'MoSPI Data Source', kind: 'glossary' },
  ],
  '/trade/hs/:code': [
    { to: '/trade', label: 'Trade Intelligence Hub', kind: 'data' },
    { to: '/intel/china', label: 'China Trade Profile', kind: 'data' },
    { to: '/intel/india', label: 'India Trade Profile', kind: 'data' },
    { to: '/glossary/current-account-balance', label: 'Current Account', kind: 'glossary' },
  ],
  '/trade/hs/:code/market/:iso': [
    { to: '/trade', label: 'Trade Intelligence Hub', kind: 'data' },
    { to: '/intel/india', label: 'India Macro Intel', kind: 'data' },
    { to: '/intel/china', label: 'China Macro Intel', kind: 'data' },
    { to: '/glossary/foreign-exchange-reserves', label: 'FX Reserve Context', kind: 'glossary' },
  ],
  '/regime-digest/:year/:month': [
    { to: '/', label: 'Live Terminal', kind: 'data' },
    { to: '/macro-observatory', label: 'Observatory', kind: 'data' },
    { to: '/labs/us-macro-fiscal', label: 'US Fiscal Lab', kind: 'lab' },
    { to: '/glossary/macro-regime-classification', label: 'Regime Classification', kind: 'glossary' },
  ],
};
