export const TIC_COUNTRY_MAPPING: Record<string, string> = {
    'Japan': 'JPN',
    'United Kingdom': 'GBR',
    'China, Mainland': 'CHN',
    'Belgium': 'BEL',
    'Luxembourg': 'LUX',
    'Canada': 'CAN',
    'Cayman Islands': 'CYM',
    'Switzerland': 'CHE',
    'Ireland': 'IRL',
    'Taiwan': 'TWN',
    'India': 'IND',
    'Hong Kong': 'HKG',
    'Singapore': 'SGP',
    'Brazil': 'BRA',
    'Norway': 'NOR',
    'France': 'FRA',
    'Germany': 'DEU',
    'Israel': 'ISR',
    'Netherlands': 'NLD',
    'Korea, Republic of': 'KOR',
    'Saudi Arabia': 'SAU',
    'United Arab Emirates': 'ARE',
    'Mexico': 'MEX',
    'Italy': 'ITA',
    'Spain': 'ESP',
    'Australia': 'AUS',
    'Kuwait': 'KWT',
    'Thailand': 'THA',
    'Bermuda': 'BMU',
    'Sweden': 'SWE',
    'Vietnam': 'VNM',
    'Poland': 'POL',
    'Chile': 'CHL',
    'Iraq': 'IRQ',
    'Colombia': 'COL',
    'Philippines': 'PHL',
    'South Africa': 'ZAF',
    'Denmark': 'DNK',
    'Turkey': 'TUR',
    'Indonesia': 'IDN',
    'Peru': 'PER',
    'Malaysia': 'MYS'
};

export const getISO3FromTIC = (ticName: string) => {
    return TIC_COUNTRY_MAPPING[ticName] || null;
};
