#!/usr/bin/env tsx

/**
 * FRED Series Discovery Script
 *
 * Queries FRED API to check which series exist for our target countries.
 * Helps build the FRED_SERIES_MAP for ingest-country-metrics.
 *
 * Usage: FRED_API_KEY=your_key npx tsx scripts/discover-fred-series.ts
 */

interface FredSeries {
  id: string;
  title: string;
  units: string;
  frequency: string;
  observation_start: string;
  observation_end: string;
}

interface SeriesInfo {
  exists: boolean;
  series?: FredSeries;
  error?: string;
}

const TARGET_COUNTRIES = [
  'US', 'GB', 'DE', 'FR', 'IT', 'JP', 'CA', 'AU', 'BR', 'AR', 'MX', 'CN', 'IN', 'KR', 'ID', 'SA', 'TR', 'RU', 'ZA',
  'SG', 'CH', 'TH', 'MY', 'AE', 'QA', 'IL', 'CL', 'NL', 'ES', 'VN', 'PH', 'EG', 'NG', 'KW', 'NO', 'SE', 'PL', 'GR', 'IE'
];

const FRED_API_KEY = process.env.FRED_API_KEY;

if (!FRED_API_KEY) {
  console.error('❌ FRED_API_KEY environment variable is required');
  console.error('   Set: export FRED_API_KEY=your_key');
  process.exit(1);
}

// Series patterns to test
const SERIES_PATTERNS: Record<string, (iso: string) => string> = {
  // FX Reserves (TRESEG{ISO}M052N) - Millions USD
  fx_reserves_bn: (iso) => `TRESEG${iso}M052N`,

  // 2Y Yields - Various patterns
  yield_2y_pct: (iso) => {
    const mapping: Record<string, string> = {
      US: 'DGS2',
      CN: 'INTDSRCNM024N',
      GB: 'IRLTLT02GBM156N',
      DE: 'IRLTLT02DEM156N',
      FR: 'IRLTLT02FRM156N',
      IT: 'IRLTLT02ITM156N',
      JP: 'IRLTLT02JPM156N',
      CA: 'IRLTLT02CAM156N',
      AU: 'IRLTLT02AUM156N',
    };
    return mapping[iso] || `IRLTLT02${iso}M156N`;
  },

  // 10Y Yields
  yield_10y_pct: (iso) => {
    const mapping: Record<string, string> = {
      US: 'DGS10',
      CN: 'INTDSRCNM193N',
      GB: 'IRLTLT03GBM156N',  // UK 10Y often uses 3Y in IFS naming
      DE: 'IRLTLT03DEM156N',
      FR: 'IRLTLT03FRM156N',
      IT: 'IRLTLT03ITM156N',
      JP: 'IRLTLT03JPM156N',
      CA: 'IRLTLT03CAM156N',
      AU: 'IRLTLT03AUM156N',
    };
    return mapping[iso] || `IRLTLT03${iso}M156N`;
  }
};

async function checkSeries(seriesId: string): Promise<SeriesInfo> {
  const url = `https://api.stlouisfed.org/fred/series/series?series_id=${seriesId}&api_key=${FRED_API_KEY}&file_type=json`;

  try {
    const res = await fetch(url);
    const data = await res.json();

    if (data.series && data.series.length > 0) {
      return { exists: true, series: data.series[0] };
    } else {
      return { exists: false, error: 'Series not found' };
    }
  } catch (e: any) {
    return { exists: false, error: e.message };
  }
}

async function discoverForCountry(iso: string): Promise<Record<string, SeriesInfo>> {
  const results: Record<string, SeriesInfo> = {};

  for (const [metricKey, patternFn] of Object.entries(SERIES_PATTERNS)) {
    const seriesId = patternFn(iso);
    const result = await checkSeries(seriesId);
    results[metricKey] = result;

    // Rate limiting: 100ms between checks
    await new Promise(r => setTimeout(r, 100));
  }

  return results;
}

async function main() {
  console.log('🔍 FRED Series Discovery for 39 Target Countries\n');
  console.log('This will check ~117 series and may take 5-10 minutes.\n');

  const coverageMap: Record<string, Record<string, string>> = {
    fx_reserves_bn: {},
    yield_2y_pct: {},
    yield_10y_pct: {}
  };

  const missingMap: Record<string, string[]> = {
    fx_reserves_bn: [],
    yield_2y_pct: [],
    yield_10y_pct: []
  };

  let totalChecks = 0;
  let totalFound = 0;

  for (let i = 0; i < TARGET_COUNTRIES.length; i++) {
    const iso = TARGET_COUNTRIES[i];
    console.log(`[${i + 1}/${TARGET_COUNTRIES.length}] ${iso}...`);

    const results = await discoverForCountry(iso);

    for (const [metric, info] of Object.entries(results)) {
      if (info.exists) {
        coverageMap[metric][iso] = info.series!.id;
        totalFound++;
      } else {
        missingMap[metric].push(iso);
      }
      totalChecks++;
    }
  }

  console.log('\n✅ Discovery Complete!\n');
  console.log('=== Coverage Summary ===\n');

  for (const metric of ['fx_reserves_bn', 'yield_2y_pct', 'yield_10y_pct']) {
    const covered = Object.keys(coverageMap[metric]).length;
    const missing = missingMap[metric].length;
    console.log(`${metric}: ${covered}/${TARGET_COUNTRIES.length} countries (${missing} missing)`);
  }

  console.log('\n=== FRED_SERIES_MAP Expansion ===\n');

  console.log('// Auto-generated by scripts/discover-fred-series.ts');
  console.log('const FRED_SERIES_MAP: Record<string, Record<string, string>> = {');

  for (const metric of ['fx_reserves_bn', 'yield_2y_pct', 'yield_10y_pct']) {
    console.log(`  ${metric}: {`);
    const entries = Object.entries(coverageMap[metric]).sort((a, b) => a[0].localeCompare(b[0]));
    for (const [iso, seriesId] of entries) {
      console.log(`    ${iso}: '${seriesId}',`);
    }
    console.log('  },');
  }

  console.log('};');

  console.log('\n=== Missing Countries (Manual Research Needed) ===\n');
  for (const metric of ['fx_reserves_bn', 'yield_2y_pct', 'yield_10y_pct']) {
    if (missingMap[metric].length > 0) {
      console.log(`${metric}: ${missingMap[metric].join(', ')}`);
    }
  }

  console.log(`\n📊 Total: ${totalFound}/${totalChecks} series found (${Math.round(totalFound/totalChecks*100)}% coverage)`);

  // Save detailed results to JSON for reference
  const outFile = 'fred-discovery-results.json';
  import('fs').then(fs => {
    fs.writeFileSync(outFile, JSON.stringify({
      coverage: coverageMap,
      missing: missingMap,
      summary: {
        totalChecks,
        totalFound,
        coveragePct: totalFound / totalChecks
      }
    }, null, 2));
    console.log(`\n💾 Detailed results saved to: ${outFile}`);
  });
}

await main();
