-- SUPERSEDED BY 20260613000000_canonical_crons.sql
-- Original: Scheduled ingest-imf-brics-monthly (0 3 1 * *)
-- All cron schedule operations in this migration were unscheduled and rescheduled
-- with the safe COALESCE + x-cron-secret vault pattern on 2026-06-13.
-- This file is retained as a historical record only — do not re-apply.
