CREATE TABLE IF NOT EXISTS public.india_institutional_observation_revisions (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  metric_id text NOT NULL,
  as_of_date date NOT NULL,
  value numeric,
  source_ref text,
  source_hash text NOT NULL,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  superseded_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_india_institutional_observation_revisions_metric_date
  ON public.india_institutional_observation_revisions (metric_id, as_of_date);

ALTER TABLE public.india_institutional_observation_revisions ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Service role read access on india institutional revisions"
  ON public.india_institutional_observation_revisions FOR SELECT TO service_role USING (true);
GRANT SELECT, INSERT ON public.india_institutional_observation_revisions TO service_role;
GRANT USAGE, SELECT ON SEQUENCE public.india_institutional_observation_revisions_id_seq TO service_role;

CREATE TABLE IF NOT EXISTS public.india_institutional_sector_revisions (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sector_key text NOT NULL,
  report_period_end date NOT NULL,
  equity_flow_inr_crore numeric,
  equity_aum_inr_crore numeric,
  source_url text,
  source_hash text NOT NULL,
  superseded_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_india_institutional_sector_revisions_key_date
  ON public.india_institutional_sector_revisions (sector_key, report_period_end);

ALTER TABLE public.india_institutional_sector_revisions ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Service role read access on india institutional sector revisions"
  ON public.india_institutional_sector_revisions FOR SELECT TO service_role USING (true);
GRANT SELECT, INSERT ON public.india_institutional_sector_revisions TO service_role;
GRANT USAGE, SELECT ON SEQUENCE public.india_institutional_sector_revisions_id_seq TO service_role;

COMMENT ON TABLE public.india_institutional_observation_revisions IS
  'Superseded India institutional observations retained for correction auditability.';

ALTER TABLE public.india_institutional_sector_observations
  ADD COLUMN IF NOT EXISTS source_name text NOT NULL DEFAULT 'NSDL',
  ADD COLUMN IF NOT EXISTS native_frequency text NOT NULL DEFAULT 'fortnightly';
