-- SUPERSEDED BY 20260613000000_canonical_crons.sql
-- Original: Unscheduled all jobs, created schedule_standard_cron helper, rescheduled ~22 jobs,
--           dropped helper. No persistent schema — only cron operations.
-- All cron schedule operations in this migration were unscheduled and rescheduled
-- with the safe COALESCE + x-cron-secret vault pattern on 2026-06-13.
-- This file is retained as a historical record only — do not re-apply.
