-- SUPERSEDED BY 20260613000000_canonical_crons.sql
-- Original: Unscheduled ingest-upi-autopay-daily and ingest-upi-autopay-monthly,
--           rescheduled ingest-upi-autopay-daily (30 8 * * *).
-- All cron schedule operations in this migration were unscheduled and rescheduled
-- with the safe COALESCE + x-cron-secret vault pattern on 2026-06-13.
-- This file is retained as a historical record only — do not re-apply.
