-- SUPERSEDED BY 20260613000000_canonical_crons.sql
-- Original: Created tmp_schedule_cie_cron helper, scheduled ingest-cie-fundamentals-daily
--           and compute-cie-macro-scores-daily, dropped helper. No persistent schema.
-- All cron schedule operations in this migration were unscheduled and rescheduled
-- with the safe COALESCE + x-cron-secret vault pattern on 2026-06-13.
-- This file is retained as a historical record only — do not re-apply.
