-- SUPERSEDED BY 20260613000000_canonical_crons.sql
-- Original: Unscheduled and rescheduled ingest-trade-intelligence-pulse (0 5 * * 0)
--           and ingest-un-comtrade-weekly (0 6 * * 0). No persistent schema.
-- All cron schedule operations in this migration were unscheduled and rescheduled
-- with the safe COALESCE + x-cron-secret vault pattern on 2026-06-13.
-- This file is retained as a historical record only — do not re-apply.
