-- SUPERSEDED BY 20260613000000_canonical_crons.sql
-- Original: Fixed ingest-trade-imports-weekly auth (SERVICE_ROLE_KEY not SUPABASE_SERVICE_ROLE_KEY)
--           plus a one-time backfill HTTP POST (already executed). No persistent schema.
-- All cron schedule operations in this migration were unscheduled and rescheduled
-- with the safe COALESCE + x-cron-secret vault pattern on 2026-06-13.
-- This file is retained as a historical record only — do not re-apply.
