-- =====================================================
-- Migration: Create FOMC Minutes Analysis Table & Cron
-- Date: 2026-05-21
-- =====================================================

CREATE TABLE IF NOT EXISTS public.fomc_minutes_analysis (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    meeting_date DATE NOT NULL UNIQUE,
    release_date DATE NOT NULL,
    overall_tone VARCHAR(50) NOT NULL,
    key_themes JSONB NOT NULL,
    notable_shifts TEXT NOT NULL,
    capital_implications TEXT NOT NULL,
    actionable_insight TEXT NOT NULL,
    raw_analysis TEXT NOT NULL,
    pdf_url TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Comments for documentation
COMMENT ON TABLE public.fomc_minutes_analysis IS 'Stores elite qualitative and structured CIO-grade macro analysis generated by OpenRouter from parsed FOMC minutes.';
COMMENT ON COLUMN public.fomc_minutes_analysis.meeting_date IS 'The date of the FOMC meeting itself (unique key constraint).';
COMMENT ON COLUMN public.fomc_minutes_analysis.overall_tone IS 'Synthesized overall bias of the central bank stance (e.g. Hawkish, Dovish, Neutral, Hawkish Shift, Dovish Shift).';
COMMENT ON COLUMN public.fomc_minutes_analysis.raw_analysis IS 'Detailed verbatim qualitative CIO macro advisory markdown generated from Claude 3.5 Sonnet.';

-- Enable Row Level Security (RLS)
ALTER TABLE public.fomc_minutes_analysis ENABLE ROW LEVEL SECURITY;

-- Allow public read-only access (frontend client)
CREATE POLICY "Allow public read access on fomc_minutes_analysis"
    ON public.fomc_minutes_analysis FOR SELECT
    TO public
    USING (true);

-- Allow full access for service_role (Edge Functions / Ingestion jobs)
CREATE POLICY "Allow service_role full access on fomc_minutes_analysis"
    ON public.fomc_minutes_analysis FOR ALL
    TO service_role
    USING (true)
    WITH CHECK (true);

-- Performance index
CREATE INDEX IF NOT EXISTS idx_fomc_minutes_analysis_meeting_date ON public.fomc_minutes_analysis(meeting_date);

-- Unschedule duplicate cron tasks if previously registered
DO $$
BEGIN
    PERFORM cron.unschedule('check-fomc-minutes-daily');
EXCEPTION WHEN OTHERS THEN NULL;
END $$;

-- Register scheduled pg_cron job to check for new releases every 2 days at 06:00 UTC
SELECT cron.schedule(
    'check-fomc-minutes-daily',
    '0 6 */2 * *', -- 06:00 UTC every 2 days
    $$
    SELECT net.http_post(
        url := 'https://debdriyzfcwvgrhzzzre.supabase.co/functions/v1/check-fomc-minutes',
        headers := jsonb_build_object(
            'Content-Type', 'application/json',
            'Authorization', 'Bearer ' || (SELECT decrypted_secret FROM vault.decrypted_secrets WHERE name = 'SUPABASE_SERVICE_ROLE_KEY' LIMIT 1)
        ),
        body := '{}'::jsonb,
        timeout_milliseconds := 600000 -- 10 mins timeout bounds for Claude response execution
    ) AS request_id;
    $$
);
