-- SUPERSEDED BY 20260613000000_canonical_crons.sql
-- Original: One-time backfill HTTP POSTs to generate-monthly-regime-digest for
--           2026-05 and 2026-06. Both requests already executed; no persistent schema.
-- This file is retained as a historical record only — do not re-apply.
