-- SUPERSEDED BY 20260613000000_canonical_crons.sql
-- Original: Master cron consolidation — enabled pg_cron extension, unscheduled all jobs,
--           created schedule_standard_cron(TEXT,TEXT,TEXT,INTEGER) helper (not dropped),
--           and rescheduled ~40 jobs. Helper function superseded by canonical migration.
-- All cron schedule operations in this migration were unscheduled and rescheduled
-- with the safe COALESCE + x-cron-secret vault pattern on 2026-06-13.
-- This file is retained as a historical record only — do not re-apply.
